const api='http://127.0.0.1:8080/api';let cavalos=[],participantes=[];
const moeda=v=>Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const escapar=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function requisitar(url,opcoes={}){const r=await fetch(url,opcoes);const d=await r.json();if(!r.ok)throw Error(d.erro||'Não foi possível concluir a operação.');return d;}
async function carregar(){try{await requisitar(`${api}/resetar`,{method:'POST'});[cavalos,participantes]=await Promise.all([requisitar(`${api}/cavalos`),requisitar(`${api}/participantes`)]);renderizar();}catch(e){document.querySelector('#catalogo').innerHTML='<p>Backend offline. Inicie o programa Java.</p>';}}
function renderizar(){const q=document.querySelector('#busca').value.toLowerCase();document.querySelector('#catalogo').innerHTML=cavalos.filter(c=>c.nome.toLowerCase().includes(q)).map(c=>`<article class="card"><h3>${escapar(c.nome)}</h3><p>${escapar(c.raca)} · ${c.idade} anos · ${escapar(c.sexo)}</p><div class="price">Lance atual: ${moeda(c.lanceAtual)}</div><small>${c.leilaoEncerrado?'Encerrado':c.leilaoAtivo?'Em andamento':'Disponível'}</small><button data-id="${c.id}">${c.leilaoEncerrado?'Ver opções':'Abrir leilão'}</button></article>`).join('')||'<p>Nenhum cavalo encontrado.</p>';document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>abrir(Number(b.dataset.id)));}
async function abrir(id){try{const c=cavalos.find(x=>x.id===id);const l=await requisitar(`${api}/leiloes/${id}`,c.leilaoAtivo||c.leilaoEncerrado?{}:{method:'POST'});const acao=prompt(`Leilão: ${l.cavalo.nome}\nLance atual: ${moeda(l.cavalo.lanceAtual)}\nDigite: lance, historico, encerrar ou reabrir`);if(!acao)return;if(acao.toLowerCase()==='historico'){alert(l.lances.map(x=>`${x.participante}: ${moeda(x.valor)}`).join('\n')||'Nenhum lance.');return;}if(acao.toLowerCase()==='encerrar'||acao.toLowerCase()==='reabrir'){await requisitar(`${api}/leiloes/${id}/${acao.toLowerCase()}`,{method:'POST'});alert(`Leilão ${acao}do.`);await carregar();return;}const valor=acao.toLowerCase()==='lance'?prompt('Valor do lance:'):acao;const p=prompt('ID do participante (1 ou 2):');if(!valor||!p)return;await requisitar(`${api}/leiloes/${id}/lances`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:`participanteId=${encodeURIComponent(p)}&valor=${encodeURIComponent(valor)}`});alert('Lance registrado.');await carregar();}catch(e){alert(e.message);}}
function cadastrar(){document.querySelector('#cadastro').hidden=false;document.querySelector('#mensagem').textContent='';document.querySelector('#form-cadastro').querySelector('input').focus();}
async function salvarParticipante(evento){evento.preventDefault();const form=evento.target;const mensagem=document.querySelector('#mensagem');try{const dados=new FormData(form);const p=await requisitar(`${api}/participantes`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:`nome=${encodeURIComponent(dados.get('nome'))}&cpf=${encodeURIComponent(dados.get('cpf'))}`});mensagem.textContent=`Participante cadastrado com ID ${p.id}.`;form.reset();await carregar();}catch(e){mensagem.textContent=e.message;}}
document.querySelector('#busca').addEventListener('input',renderizar);carregar();
